name: test

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'LICENSE'
      - '*.md'
      - '.github/**'
  pull_request:
    branches:
      - master
    types:
      - opened
      - reopened
      - synchronize
    paths-ignore:
      - '.github/**'
      - 'LICENSE'
      - '*.md'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macOS-latest
        nim:
          - 1.4.8
          - stable
    name: Nim ${{ matrix.nim }} (${{ matrix.os }})
    steps:
      - uses: actions/checkout@v2
      - name: Cache nimble
        id: cache-nimble
        uses: actions/cache@v2
        with:
          path: ~/.nimble
          key: ${{ runner.os }}-nimble-${{ matrix.nim }}
        if: runner.os != 'Windows'
      - name: Set up Nim
        uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: ${{ matrix.nim }}
      - name: Print Nim version
        run: nim -v
      - name: Print Nimble version
        run: nimble -v
      - name: Run Nimble tests
        run: nimble test -y
      - name: Build with Nimble
        run: nimble build -y
